font="Maple Mono NF"
prompt="~> "
icons-enabled=no
lines=8
width=25
horizontal-pad=20
inner-pad = 10

[border]
width = 3
radius = 10

# Gruvbox color theme
[colors]
background=282828ff
text=fbf1c7ff
prompt=8ec07cff
placeholder=83a598ff
input=ebdbb2ff
match=83a598ff
selection=ebdbb280
selection-text=fbf1c7ff
selection-match=282828ff
counter=8ec07cff
border=ebdbb2ff
